# The Narrative Structure of the Popol Wuj

## Abstract

This essay proposes a novel division of the Popol Wuj into parts and chapters based on the application of structuralist narratology supported by classical text analytic methods. It is proposed that the text comprises eight chapters belonging to two parts: part one contains five chapters oriented toward events before the first dawn, while part two contains three chapters concerning events following the dawn. These divisions form an integrated mythohistoric sequence that connects the actions of metahuman agents, or gods, to those of divine kings up to the time of the Spanish conquest. The connection between myth and history is represented in temporal and causal terms, in the sense of myth preceding and producing history, and structurally, in the sense that the mythic and historic chapters exhibit a parallel structure centered on the pivotal act of sacrifice. It is argued that although the text may have been composed in direct response to Vico’s *Theologia Indorum*, the thematic unity of the text exhibits a deep patterning reflective of an indigenous Maya historicity.

## Introduction

The K’iche’ Maya Popol Wuj[^1] is arguably the most significant surviving indigenous written text from the Americas. Its combination of word length, narrative sweep, and thematic unity have no counterpart in the Western hemisphere among extant literary artifacts. From a comparative perspective the Popol Wuj belongs to a mythohistoric genre that includes the Babylonian *Epic of Gilgamesh*, the Indian *Ramayana*, the Persian *Shahnameh*, and other foundational texts that recount the exploits of metahuman beings and their connections to living kings. Since coming into the hands of European scholars in the mid-nineteenth century, the text has been translated into at least twenty-five languages, and new editions, both scholarly and popular, continue to appear.

[^1]: This essay adopts this spelling over the more common *Popol Vuh*. By PW, we refer to the text contained in the manuscript composed in the 16^th^ century.

Because of its unique status, the Popol Wuj has long been regarded by scholars as a “window into the mind of the Ancient Maya” (Christenson and Sachse 2021: 3), providing a view relatively untainted by the beliefs and practices brutally imposed by their Spanish Catholic conquerors. Following the lead of Michael Coe (1973), the text has served as a key to the interpretation of numerous scenes depicted on carved and painted artifacts from the lowland preclassic and classic periods. Specific characters and episodes from the story have been identified on items dated to 300 BCE, two millennia before the composition of the current text.

Recently this view has been challenged.

Corroborated by the arbitrary nature of its assigned part and chapter divisions in its various editions.

Also argued that it is a western imposition, epistemic imperialism.

Unity on the division at Ch 41.

Continue to state hypothesis ...

## Mythohistory

## Structuralist narratology

## Existing divisions