"""
Annotation Coverage — completeness analysis of <rs> markup in the Ximenez XML.

Loads three CSVs produced by notebooks/ximenez/tema_coverage.py:
  ximenez-SURFACE_FORMS.csv  — all spelling variants per tema
  ximenez-COVERAGE.csv       — per-tema annotation vs. text-occurrence counts
  ximenez-MISSED.csv         — candidate missed annotations (Levenshtein near-matches)
"""

import os
import yaml
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

APP_DIR = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(APP_DIR, "../config.yaml"), encoding="utf-8") as _f:
    cfg = yaml.safe_load(_f)

st.markdown(
    f"<style>.block-container{{max-width:{cfg['layout']['max_width_px']}px !important;}}</style>",
    unsafe_allow_html=True,
)

SURFACE_FORMS_PATH = os.path.normpath(
    os.path.join(APP_DIR, "../../notebooks/ximenez/ximenez-SURFACE_FORMS.csv")
)
COVERAGE_PATH = os.path.normpath(
    os.path.join(APP_DIR, "../../notebooks/ximenez/ximenez-COVERAGE.csv")
)
MISSED_PATH = os.path.normpath(
    os.path.join(APP_DIR, "../../notebooks/ximenez/ximenez-MISSED.csv")
)


@st.cache_data(show_spinner="Loading annotation data…")
def load_all():
    sf = pd.read_csv(SURFACE_FORMS_PATH)
    cv = pd.read_csv(COVERAGE_PATH)
    ms = pd.read_csv(MISSED_PATH)
    return sf, cv, ms


SF, CV, MS = load_all()

st.title("Annotation Coverage — Ximenez Manuscript")
st.caption(
    "Analysis of `<rs ana=\"...\">` markup completeness in the Ximenez K'iche' column. "
    "Generated by `notebooks/ximenez/tema_coverage.py` from `xom-all-flat-mod-pnums.xml`."
)

with st.expander("Method", expanded=False):
    st.markdown("""
**Surface forms** are extracted directly from the `#PCDATA` content of every `<rs>` element in
the K'iche' column (`<div xml:lang="quc">`). Each surface form is character-normalized
(e.g., ꜩ → tz, ÿ → i, accents stripped) and stored per `ana_id`.

**Exact coverage** counts how many `<lb>` lines contain at least one surface form for each tema
(after the same normalization). `coverage_ratio = n_annotated / n_found_exact`.

- ratio ≈ 1 → annotations track text occurrences closely
- ratio < 1 → more occurrences in text than annotations (selective markup or missed instances)
- ratio > 1 → fewer text matches than annotations (compound words, line-break splits, or forms
  not captured by the surface-form inventory)

**Missed annotation candidates** are generated by sliding 1–4 token windows over every unannotated
line and comparing each phrase to all known surface forms using `rapidfuzz.fuzz.ratio`
(Levenshtein similarity, 0–100). Only temas with ≥ 3 annotations and forms ≥ 4 characters are
tested. Candidates scoring ≥ 85 are reported.
""")

_tab_ov, _tab_sf, _tab_miss = st.tabs([
    "Coverage Overview", "Surface Forms", "Missed Candidates"
])

# ── Tab 1: Coverage overview ──────────────────────────────────────────────────
with _tab_ov:
    st.caption(
        f"{len(CV)} temas · {CV['n_annotated'].sum():,} total annotations · "
        f"{len(SF):,} surface form variants"
    )

    _cols = st.columns([2, 1])

    # Scatter: n_annotated vs n_found_exact
    cv_plot = CV.dropna(subset=["coverage_ratio"]).copy()
    cv_plot["ratio_clamp"] = cv_plot["coverage_ratio"].clip(0, 2)
    fig_sc = px.scatter(
        cv_plot,
        x="n_found_exact",
        y="n_annotated",
        color="ratio_clamp",
        color_continuous_scale="RdYlGn",
        range_color=[0, 2],
        hover_name="ana_id",
        hover_data={"n_found_exact": True, "n_annotated": True,
                    "coverage_ratio": ":.3f", "ratio_clamp": False},
        labels={
            "n_found_exact": "Exact text matches",
            "n_annotated":   "Annotations",
            "ratio_clamp":   "Coverage ratio (clamped 0–2)",
        },
        title="Annotations vs. Text Occurrences",
    )
    # Diagonal reference line (ratio = 1)
    _mx = max(cv_plot["n_found_exact"].max(), cv_plot["n_annotated"].max())
    fig_sc.add_shape(type="line", x0=0, y0=0, x1=_mx, y1=_mx,
                     line=dict(dash="dash", color="gray", width=1))
    fig_sc.update_layout(height=420, margin=dict(l=60, r=20, t=40, b=60))
    _cols[0].plotly_chart(fig_sc, width="stretch")

    # Ratio distribution histogram
    bins = [0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 999]
    labels = ["<0.10", "0.10–0.25", "0.25–0.50", "0.50–0.75",
              "0.75–1.00", "1.00–1.50", ">1.50"]
    cv_plot["ratio_bin"] = pd.cut(cv_plot["coverage_ratio"], bins=bins, labels=labels)
    bin_counts = cv_plot["ratio_bin"].value_counts().reindex(labels, fill_value=0)
    fig_bar = px.bar(
        x=bin_counts.index, y=bin_counts.values,
        labels={"x": "Coverage ratio", "y": "Number of temas"},
        title="Coverage Ratio Distribution",
        color=bin_counts.index,
        color_discrete_sequence=px.colors.diverging.RdYlGn,
    )
    fig_bar.update_layout(height=420, showlegend=False,
                          margin=dict(l=60, r=20, t=40, b=60))
    _cols[1].plotly_chart(fig_bar, width="stretch")

    st.subheader("Full Coverage Table")
    cv_disp = CV.sort_values("n_annotated", ascending=False).copy()
    cv_disp["coverage_ratio"] = cv_disp["coverage_ratio"].round(3)
    st.dataframe(cv_disp, width="stretch")

# ── Tab 2: Surface forms ──────────────────────────────────────────────────────
with _tab_sf:
    st.caption(
        "All spelling variants extracted from `<rs>` PCDATA in the K'iche' column, "
        "after character normalization."
    )

    _c2 = st.columns([2, 1])
    _ana_opts = sorted(SF["ana_id"].unique())
    sel_ids = _c2[0].multiselect(
        "Filter by tema (ana_id)", _ana_opts,
        default=[], placeholder="All temas"
    )
    min_tokens = _c2[1].slider("Min token length", 1, 4, 1)

    sf_disp = SF.copy()
    if sel_ids:
        sf_disp = sf_disp[sf_disp["ana_id"].isin(sel_ids)]
    sf_disp = sf_disp[sf_disp["form_length"] >= min_tokens]
    sf_disp = sf_disp.sort_values(["n_annotated", "ana_id", "form_length"],
                                  ascending=[False, True, False])

    st.caption(f"{len(sf_disp):,} surface forms shown.")
    st.dataframe(sf_disp, width="stretch")

# ── Tab 3: Missed annotation candidates ──────────────────────────────────────
with _tab_miss:
    st.caption(
        f"{len(MS):,} unique candidates · Levenshtein similarity ≥ 85 · "
        "temas with ≥ 3 annotations only."
    )

    _cm = st.columns([1, 1, 1])
    score_min = _cm[0].slider("Min similarity score", 85, 100, 90, step=1)
    _ana_opts2 = sorted(MS["ana_id"].unique())
    sel_ids2 = _cm[1].multiselect(
        "Filter by tema", _ana_opts2, default=[], placeholder="All temas"
    )
    folio_min, folio_max = int(MS["folio"].min()), int(MS["folio"].max())
    folio_range = _cm[2].slider(
        "Folio range", folio_min, folio_max, (folio_min, folio_max)
    )

    ms_disp = MS[MS["score"] >= score_min].copy()
    if sel_ids2:
        ms_disp = ms_disp[ms_disp["ana_id"].isin(sel_ids2)]
    ms_disp = ms_disp[
        ms_disp["folio"].between(folio_range[0], folio_range[1])
    ]
    ms_disp = ms_disp.sort_values("score", ascending=False)

    st.caption(f"**{len(ms_disp):,}** candidates match current filters.")

    # Summary: how many candidates per tema at this threshold
    _summary = (
        ms_disp.groupby("ana_id")
        .agg(candidates=("score", "count"), max_score=("score", "max"))
        .sort_values("candidates", ascending=False)
        .head(20)
        .reset_index()
    )
    fig_top = px.bar(
        _summary, x="ana_id", y="candidates",
        color="max_score", color_continuous_scale="Oranges",
        labels={"ana_id": "Tema", "candidates": "Candidate count",
                "max_score": "Best score"},
        title="Top 20 Temas by Missed-Annotation Candidates",
    )
    fig_top.update_layout(height=320, margin=dict(l=60, r=20, t=40, b=120),
                          xaxis_tickangle=-45)
    st.plotly_chart(fig_top, width="stretch")

    st.subheader("Candidate Table")
    ms_show = ms_disp[["folio", "side", "para_num", "lb_n",
                        "found_phrase", "matched_form", "ana_id", "score", "line_text"]]
    st.dataframe(ms_show, width="stretch")
